CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('OWNER','MANAGER','SALESMAN'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE tx_status AS ENUM ('PENDING','VERIFIED','REJECTED','LOCKED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_mode AS ENUM ('CASH','UPI','CARD','BANK','FLEET','CREDIT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE bank_tx_type AS ENUM ('DIGITAL_COLLECTION','CASH_DEPOSIT','FLEET_SETTLEMENT','CREDIT_COLLECTION','SUPPLIER_PAYMENT','EXPENSE_PAYMENT','PAYROLL_PAYMENT','OWNER_WITHDRAWAL','BANK_TRANSFER_IN','BANK_TRANSFER_OUT','BANK_CHARGE','OTHER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE delivery_recovery_status AS ENUM ('PENDING','PARTIAL','RECOVERED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS stations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',currency TEXT NOT NULL DEFAULT 'INR',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),name TEXT NOT NULL,mobile TEXT NOT NULL,password_hash TEXT NOT NULL,role user_role NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(station_id,mobile));
CREATE TABLE IF NOT EXISTS shifts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),opened_by UUID NOT NULL REFERENCES users(id),status TEXT NOT NULL DEFAULT 'OPEN',shift_type TEXT NOT NULL,starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ,opening_cash NUMERIC(14,2) NOT NULL DEFAULT 0,closing_cash_actual NUMERIC(14,2),locked_at TIMESTAMPTZ,locked_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS products(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),code TEXT NOT NULL,name TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,UNIQUE(station_id,code));
CREATE TABLE IF NOT EXISTS tanks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),product_id UUID NOT NULL REFERENCES products(id),name TEXT NOT NULL,capacity_l NUMERIC(14,3) NOT NULL,opening_stock_l NUMERIC(14,3) NOT NULL DEFAULT 0,opening_dip_l NUMERIC(14,3) NOT NULL DEFAULT 0,dip_chart_id UUID,active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS bank_accounts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),name TEXT NOT NULL,account_mask TEXT,opening_balance NUMERIC(14,2) NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS deliveries(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),product_id UUID NOT NULL REFERENCES products(id),tank_id UUID NOT NULL REFERENCES tanks(id),invoice_no TEXT,invoice_qty_l NUMERIC(14,3) NOT NULL,invoice_value NUMERIC(14,2) NOT NULL,purchase_rate NUMERIC(14,6) GENERATED ALWAYS AS (CASE WHEN invoice_qty_l=0 THEN 0 ELSE invoice_value/invoice_qty_l END) STORED,shortage_l NUMERIC(14,3) NOT NULL DEFAULT 0,net_received_l NUMERIC(14,3) GENERATED ALWAYS AS (invoice_qty_l-shortage_l) STORED,pending_recovery_l NUMERIC(14,3) NOT NULL DEFAULT 0,recovery_l NUMERIC(14,3) NOT NULL DEFAULT 0,recovery_status delivery_recovery_status NOT NULL DEFAULT 'PENDING',recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),verified_at TIMESTAMPTZ,delivered_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(shortage_l>=0 AND shortage_l<=invoice_qty_l));
CREATE TABLE IF NOT EXISTS inventory_layers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),product_id UUID NOT NULL REFERENCES products(id),delivery_id UUID REFERENCES deliveries(id),quantity_received_l NUMERIC(14,3) NOT NULL,quantity_remaining_l NUMERIC(14,3) NOT NULL,cost_per_l NUMERIC(14,6) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(quantity_received_l>=0 AND quantity_remaining_l>=0 AND quantity_remaining_l<=quantity_received_l));
CREATE TABLE IF NOT EXISTS sales(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID NOT NULL REFERENCES shifts(id),product_id UUID NOT NULL REFERENCES products(id),nozzle TEXT NOT NULL,quantity_l NUMERIC(14,3) NOT NULL,rate NUMERIC(14,6) NOT NULL,amount NUMERIC(14,2) GENERATED ALWAYS AS (quantity_l*rate) STORED,payment_mode payment_mode NOT NULL,customer_name TEXT,company_name TEXT,vehicle_no TEXT,status tx_status NOT NULL DEFAULT 'PENDING',cogs_amount NUMERIC(14,2),margin_amount NUMERIC(14,2),recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(quantity_l>0 AND rate>=0));
CREATE TABLE IF NOT EXISTS collections(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID REFERENCES shifts(id),source_type TEXT NOT NULL,source_id UUID,payment_mode payment_mode NOT NULL,amount NUMERIC(14,2) NOT NULL,settlement_status tx_status NOT NULL DEFAULT 'PENDING',recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(source_type,source_id,payment_mode),CHECK(amount>0));
CREATE TABLE IF NOT EXISTS bank_transactions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),bank_account_id UUID NOT NULL REFERENCES bank_accounts(id),type bank_tx_type NOT NULL,direction TEXT NOT NULL CHECK(direction IN ('IN','OUT')),amount NUMERIC(14,2) NOT NULL,source_type TEXT,source_id UUID,reference TEXT,status tx_status NOT NULL DEFAULT 'PENDING',recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(source_type,source_id,type),CHECK(amount>0));
CREATE TABLE IF NOT EXISTS expenses(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID REFERENCES shifts(id),category TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,payment_mode payment_mode NOT NULL,purpose TEXT NOT NULL,status tx_status NOT NULL DEFAULT 'PENDING',recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(amount>0));
CREATE TABLE IF NOT EXISTS supplier_payments(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),supplier_name TEXT NOT NULL,invoice_no TEXT,amount NUMERIC(14,2) NOT NULL,payment_mode payment_mode NOT NULL,bank_account_id UUID REFERENCES bank_accounts(id),status tx_status NOT NULL DEFAULT 'PENDING',recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(amount>0));
CREATE TABLE IF NOT EXISTS payroll_runs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),month_start DATE NOT NULL,month_end DATE NOT NULL,total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,status tx_status NOT NULL DEFAULT 'PENDING',prepared_by UUID NOT NULL REFERENCES users(id),approved_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reconciliation(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID NOT NULL REFERENCES shifts(id) UNIQUE,expected_cash NUMERIC(14,2) NOT NULL DEFAULT 0,actual_cash NUMERIC(14,2),cash_variance NUMERIC(14,2),status TEXT NOT NULL DEFAULT 'PENDING',reason TEXT,decided_by UUID REFERENCES users(id),decided_at TIMESTAMPTZ);
ALTER TABLE tanks ADD COLUMN IF NOT EXISTS opening_stock_l NUMERIC(14,3) NOT NULL DEFAULT 0;
ALTER TABLE tanks ADD COLUMN IF NOT EXISTS opening_dip_l NUMERIC(14,3) NOT NULL DEFAULT 0;
ALTER TABLE tanks ADD COLUMN IF NOT EXISTS dip_chart_id UUID;
ALTER TABLE expenses_v14 ADD COLUMN IF NOT EXISTS status tx_status NOT NULL DEFAULT 'PENDING';
ALTER TABLE expenses_v14 ADD COLUMN IF NOT EXISTS verified_by UUID REFERENCES users(id);
ALTER TABLE expenses_v14 ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS dip_chart_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),name TEXT NOT NULL,product_id UUID NOT NULL REFERENCES products(id),tank_id UUID REFERENCES tanks(id),version_no INTEGER NOT NULL DEFAULT 1,points_json JSONB NOT NULL DEFAULT '[]'::jsonb,active BOOLEAN NOT NULL DEFAULT true,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(station_id,name,version_no));

CREATE TABLE IF NOT EXISTS tank_dip_readings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),tank_id UUID NOT NULL REFERENCES tanks(id),reading_l NUMERIC(14,3) NOT NULL,reading_type TEXT NOT NULL DEFAULT 'VERIFIED',recorded_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS audit_events(id BIGSERIAL PRIMARY KEY,station_id UUID NOT NULL REFERENCES stations(id),actor_id UUID REFERENCES users(id),entity_type TEXT NOT NULL,entity_id UUID,action TEXT NOT NULL,before_json JSONB,after_json JSONB,reason TEXT,request_id UUID NOT NULL DEFAULT gen_random_uuid(),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS idempotency_keys(id UUID PRIMARY KEY,station_id UUID NOT NULL REFERENCES stations(id),actor_id UUID NOT NULL REFERENCES users(id),route TEXT NOT NULL,response_json JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(station_id,actor_id,route,id));
CREATE INDEX IF NOT EXISTS sales_station_date ON sales(station_id,created_at); CREATE INDEX IF NOT EXISTS bank_station_date ON bank_transactions(station_id,created_at); CREATE INDEX IF NOT EXISTS inventory_product ON inventory_layers(station_id,product_id,created_at);
CREATE OR REPLACE FUNCTION audit_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit_events are immutable'; END; $$;
DROP TRIGGER IF EXISTS audit_no_mutation ON audit_events; CREATE TRIGGER audit_no_mutation BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_immutable();

-- V13 operational control additions
CREATE TABLE IF NOT EXISTS cash_movements(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID REFERENCES shifts(id),source_type TEXT NOT NULL,source_id UUID,direction TEXT NOT NULL CHECK(direction IN ('IN','OUT')),amount NUMERIC(14,2) NOT NULL,purpose TEXT NOT NULL,recorded_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(amount>0));
CREATE INDEX IF NOT EXISTS cash_movements_station_shift ON cash_movements(station_id,shift_id,created_at);
CREATE INDEX IF NOT EXISTS reconciliation_station_status ON reconciliation(station_id,status);

-- V14 Salesman module
CREATE TABLE IF NOT EXISTS machines(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),code TEXT NOT NULL,name TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,UNIQUE(station_id,code));
CREATE TABLE IF NOT EXISTS nozzles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),machine_id UUID NOT NULL REFERENCES machines(id),code TEXT NOT NULL,product_id UUID NOT NULL REFERENCES products(id),opening_meter NUMERIC(14,3) NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT true,UNIQUE(machine_id,code));
CREATE TABLE IF NOT EXISTS shift_assignments(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),shift_id UUID NOT NULL REFERENCES shifts(id) UNIQUE,salesman_id UUID NOT NULL REFERENCES users(id),machine_id UUID REFERENCES machines(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS shift_nozzle_readings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),shift_id UUID NOT NULL REFERENCES shifts(id),nozzle_id UUID NOT NULL REFERENCES nozzles(id),opening_meter NUMERIC(14,3) NOT NULL,closing_meter NUMERIC(14,3),verified_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(shift_id,nozzle_id));
CREATE TABLE IF NOT EXISTS credit_customers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),name TEXT NOT NULL,phone TEXT,previous_outstanding NUMERIC(14,2) NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS nat_tests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID NOT NULL REFERENCES shifts(id),nozzle_id UUID NOT NULL REFERENCES nozzles(id),quantity_l NUMERIC(14,3) NOT NULL,recorded_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(quantity_l>0));
CREATE INDEX IF NOT EXISTS nozzles_station ON nozzles(station_id,active); CREATE INDEX IF NOT EXISTS customers_station ON credit_customers(station_id,active); CREATE INDEX IF NOT EXISTS nat_shift ON nat_tests(shift_id,created_at);

CREATE TABLE IF NOT EXISTS product_rates(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),product_id UUID NOT NULL REFERENCES products(id),selling_rate NUMERIC(14,6) NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT true,UNIQUE(station_id,product_id));
CREATE TABLE IF NOT EXISTS expenses_v14(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID REFERENCES shifts(id),category TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,purpose TEXT NOT NULL,payment_mode payment_mode NOT NULL DEFAULT 'CASH',status tx_status NOT NULL DEFAULT 'PENDING',recorded_by UUID NOT NULL REFERENCES users(id),verified_by UUID REFERENCES users(id),verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(amount>0));


ALTER TABLE sales ADD COLUMN IF NOT EXISTS company_name TEXT;

-- V14.1 Salesman attendance control
CREATE TABLE IF NOT EXISTS attendance(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),station_id UUID NOT NULL REFERENCES stations(id),shift_id UUID NOT NULL REFERENCES shifts(id) UNIQUE,user_id UUID NOT NULL REFERENCES users(id),status TEXT NOT NULL DEFAULT 'PRESENT',duty_days NUMERIC(4,2) NOT NULL DEFAULT 1,started_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(duty_days>0));
CREATE INDEX IF NOT EXISTS attendance_station_user ON attendance(station_id,user_id,created_at);

-- V16 owner reconciliation control
ALTER TABLE reconciliation ADD COLUMN IF NOT EXISTS owner_decision TEXT;
ALTER TABLE reconciliation ADD COLUMN IF NOT EXISTS owner_reason TEXT;
