import express from 'express';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import pg from 'pg';
import crypto from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {Pool}=pg;
const app=express();
const PORT=Number(process.env.PORT||3000);
const JWT_SECRET=process.env.JWT_SECRET||'development-only-change-me';
const pool=new Pool({connectionString:process.env.DATABASE_URL||'postgres://pumpos:pumpos@localhost:5432/pumpos'});
const __dirname=path.dirname(fileURLToPath(import.meta.url));
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'../public')));
const sign=u=>jwt.sign({sub:u.id,stationId:u.station_id,role:u.role,name:u.name},JWT_SECRET,{expiresIn:'8h'});
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error();req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch{res.status(401).json({error:'Unauthorized'});}}
const roles=(...r)=>(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:'Forbidden'});
async function tx(fn){const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
async function audit(c,u,type,id,action,before,after,reason){await c.query('INSERT INTO audit_events(station_id,actor_id,entity_type,entity_id,action,before_json,after_json,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[u.stationId,u.sub,type,id,action,before||null,after||null,reason||null]);}
async function idem(req,c,route){const key=req.headers['idempotency-key'];if(!key)return null;const id=crypto.createHash('sha256').update(`${req.user.stationId}:${req.user.sub}:${route}:${key}`).digest('hex').slice(0,32);const q=await c.query('SELECT response_json FROM idempotency_keys WHERE id=$1',[id]);if(q.rowCount)return q.rows[0].response_json;req._idem={id,route};return null;}
async function saveIdem(req,c,response){if(req._idem)await c.query('INSERT INTO idempotency_keys(id,station_id,actor_id,route,response_json) VALUES($1,$2,$3,$4,$5)',[req._idem.id,req.user.stationId,req.user.sub,req._idem.route,response]);}
function n(v){return Number(v||0);}

app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'pumpos-api',version:'22.0.0'});}catch{res.status(503).json({ok:false,error:'Database unavailable'});}});
app.get('/api/setup/status',async(_req,res)=>{try{const q=await pool.query('SELECT COUNT(*)::int AS users, COUNT(*) FILTER (WHERE role=\'OWNER\')::int AS owners, (SELECT COUNT(*) FROM stations)::int AS stations FROM users');const x=q.rows[0];res.json({initialized:Number(x.owners)>0,stations:Number(x.stations),owners:Number(x.owners),users:Number(x.users)});}catch(e){res.status(503).json({initialized:false,error:'Database unavailable'});}});
app.post('/api/setup/onboard',async(req,res)=>{try{const b=req.body||{};if(!b.ownerName||!b.ownerMobile||!b.ownerPassword||!b.stationName)throw Error('Owner And Station Details Are Required');if(String(b.ownerPassword).length<6)throw Error('Owner Password Must Be At Least 6 Characters');const products=Array.isArray(b.products)?b.products:[];const tanks=Array.isArray(b.tanks)?b.tanks:[];const machines=Array.isArray(b.machines)?b.machines:[];if(!products.length)throw Error('Add At Least One Product');if(!tanks.length)throw Error('Add At Least One Tank');if(!machines.length)throw Error('Add At Least One Machine');const out=await tx(async c=>{const existing=await c.query("SELECT id FROM users WHERE role='OWNER' LIMIT 1");if(existing.rowCount)throw Error('PumpOS Is Already Initialized');const st=(await c.query('INSERT INTO stations(name,timezone,currency) VALUES($1,$2,$3) RETURNING *',[b.stationName,b.timezone||'Asia/Kolkata',b.currency||'INR'])).rows[0];const hash=await bcrypt.hash(b.ownerPassword,12);const owner=(await c.query("INSERT INTO users(station_id,name,mobile,password_hash,role) VALUES($1,$2,$3,$4,'OWNER') RETURNING id,name,mobile,role,station_id",[st.id,b.ownerName,b.ownerMobile,hash])).rows[0];const productMap={};for(const x of products){if(!x.name)continue;const p=(await c.query('INSERT INTO products(station_id,code,name) VALUES($1,$2,$3) RETURNING *',[st.id,String(x.code||x.name).toUpperCase().replace(/\\s+/g,'_'),x.name])).rows[0];productMap[x.key||x.code||x.name]=p;}for(const x of tanks){const prod=productMap[x.productKey]||Object.values(productMap)[0];if(!prod)continue;const tank=(await c.query('INSERT INTO tanks(station_id,product_id,name,capacity_l,opening_stock_l,opening_dip_l) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[st.id,prod.id,x.name||'Tank',x.capacity||0,x.openingStock||0,x.openingDip||0])).rows[0];if(n(x.openingStock)>0)await c.query('INSERT INTO inventory_layers(station_id,product_id,quantity_received_l,quantity_remaining_l,cost_per_l) VALUES($1,$2,$3,$3,0)',[st.id,prod.id,x.openingStock]);}for(const x of machines){if(!x.name)continue;const m=(await c.query('INSERT INTO machines(station_id,code,name) VALUES($1,$2,$3) RETURNING *',[st.id,String(x.code||x.name).toUpperCase().replace(/\\s+/g,'_'),x.name])).rows[0];for(const z of (x.nozzles||[])){const prod=productMap[z.productKey]||Object.values(productMap)[0];if(prod)await c.query('INSERT INTO nozzles(station_id,machine_id,code,product_id,opening_meter) VALUES($1,$2,$3,$4,$5)',[st.id,m.id,z.code||'N1',prod.id,z.openingMeter||0]);}}await audit(c,{stationId:st.id,sub:owner.id},'ONBOARDING',st.id,'CREATE',null,{station:st.id,owner:owner.id});return {station:st,owner};});res.status(201).json({token:sign(out.owner),user:{id:out.owner.id,name:out.owner.name,role:out.owner.role,stationId:out.owner.station_id},station:out.station});}catch(e){res.status(400).json({error:e.message});}});

app.post('/api/auth/login',async(req,res)=>{try{const {mobile,password}=req.body||{};const q=await pool.query('SELECT * FROM users WHERE mobile=$1 AND active=true LIMIT 1',[mobile]);if(!q.rowCount||!(await bcrypt.compare(password,q.rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});const u=q.rows[0];res.json({token:sign(u),user:{id:u.id,name:u.name,role:u.role,stationId:u.station_id}});}catch(e){res.status(500).json({error:'Login failed'});}});
app.get('/api/me',auth,(req,res)=>res.json(req.user));

app.get('/api/bootstrap',auth,async(req,res)=>{try{const s=req.user.stationId;const [station,products,banks,shift]=await Promise.all([
 pool.query('SELECT id,name,timezone,currency FROM stations WHERE id=$1',[s]),
 pool.query('SELECT id,code,name FROM products WHERE station_id=$1 AND active=true ORDER BY code',[s]),
 pool.query('SELECT id,name,account_mask,opening_balance FROM bank_accounts WHERE station_id=$1 AND active=true ORDER BY name',[s]),
 pool.query("SELECT * FROM shifts WHERE station_id=$1 AND status='OPEN' ORDER BY starts_at DESC LIMIT 1",[s])
]);res.json({station:station.rows[0],products:products.rows,banks:banks.rows,shift:shift.rows[0]||null});}catch(e){res.status(500).json({error:'Bootstrap failed'});}});
// V14 Salesman module
app.get('/api/salesman/setup',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const s=req.user.stationId;const [m,nz,c]=await Promise.all([
 pool.query("SELECT id,code,name FROM machines WHERE station_id=$1 AND active=true ORDER BY code",[s]),
 pool.query("SELECT n.id,n.code,n.machine_id,n.product_id,n.opening_meter,m.code machine_code,m.name machine_name,p.code product_code,p.name product_name FROM nozzles n JOIN machines m ON m.id=n.machine_id JOIN products p ON p.id=n.product_id WHERE n.station_id=$1 AND n.active=true ORDER BY m.code,n.code",[s]),
 pool.query("SELECT id,name,phone,previous_outstanding FROM credit_customers WHERE station_id=$1 AND active=true ORDER BY name",[s])
]);res.json({machines:m.rows,nozzles:nz.rows,customers:c.rows});}catch(e){res.status(500).json({error:'Salesman setup failed'});}});
app.get('/api/salesman/rates',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const q=await pool.query(`SELECT p.id,p.code,p.name,r.selling_rate FROM products p LEFT JOIN product_rates r ON r.product_id=p.id AND r.station_id=p.station_id AND r.active=true WHERE p.station_id=$1 AND p.active=true ORDER BY p.code`,[req.user.stationId]);res.json(q.rows);}catch(e){res.status(500).json({error:'Rates failed'});}});

app.post('/api/salesman/assign',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const {shiftId,machineId,nozzleReadings=[]}=req.body;const out=await tx(async c=>{const sh=(await c.query("SELECT * FROM shifts WHERE id=$1 AND station_id=$2 AND status='OPEN' FOR UPDATE",[shiftId,req.user.stationId])).rows[0];if(!sh)throw Error('Open shift required');if(!machineId)throw Error('Machine is required');const machine=(await c.query('SELECT id FROM machines WHERE id=$1 AND station_id=$2 AND active=true',[machineId,req.user.stationId])).rows[0];if(!machine)throw Error('Machine not found');const a=(await c.query(`INSERT INTO shift_assignments(shift_id,salesman_id,machine_id) VALUES($1,$2,$3) ON CONFLICT(shift_id) DO UPDATE SET salesman_id=EXCLUDED.salesman_id,machine_id=EXCLUDED.machine_id RETURNING *`,[shiftId,req.user.sub,machineId])).rows[0];const allowed=(await c.query('SELECT id FROM nozzles WHERE station_id=$1 AND machine_id=$2 AND active=true',[req.user.stationId,machineId])).rows;const allowedIds=new Set(allowed.map(x=>x.id));for(const r of nozzleReadings){if(!r.nozzleId||!allowedIds.has(r.nozzleId)||n(r.openingMeter)<0)throw Error('Invalid nozzle reading');await c.query(`INSERT INTO shift_nozzle_readings(shift_id,nozzle_id,opening_meter) VALUES($1,$2,$3) ON CONFLICT(shift_id,nozzle_id) DO UPDATE SET opening_meter=EXCLUDED.opening_meter`,[shiftId,r.nozzleId,r.openingMeter]);}if(!nozzleReadings.length)throw Error('Opening meter readings are required');await c.query(`INSERT INTO attendance(station_id,shift_id,user_id,status,duty_days,started_at) VALUES($1,$2,$3,'PRESENT',CASE WHEN $4::timestamptz-$5::timestamptz>=interval '20 hours' THEN 2 ELSE 1 END,$4) ON CONFLICT(shift_id) DO UPDATE SET status='PRESENT',started_at=EXCLUDED.started_at`,[req.user.stationId,shiftId,req.user.sub,sh.ends_at||sh.starts_at,sh.starts_at]);await audit(c,req.user,'SHIFT_ASSIGNMENT',a.id,'ASSIGN',null,a,null);return a;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/salesman/shift/:id',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const s=req.user.stationId;const sh=(await pool.query("SELECT * FROM shifts WHERE id=$1 AND station_id=$2",[req.params.id,s])).rows[0];if(!sh)throw Error('Shift not found');const [a,nz,sales,nat,att]=await Promise.all([
 pool.query("SELECT a.*,u.name salesman_name,m.code machine_code,m.name machine_name FROM shift_assignments a JOIN users u ON u.id=a.salesman_id LEFT JOIN machines m ON m.id=a.machine_id WHERE a.shift_id=$1",[sh.id]),
 pool.query("SELECT r.*,n.code nozzle_code,m.code machine_code,p.code product_code,p.name product_name FROM shift_nozzle_readings r JOIN nozzles n ON n.id=r.nozzle_id JOIN machines m ON m.id=n.machine_id JOIN products p ON p.id=n.product_id WHERE r.shift_id=$1 ORDER BY m.code,n.code",[sh.id]),
 pool.query("SELECT s.*,p.code product_code,p.name product_name FROM sales s JOIN products p ON p.id=s.product_id WHERE s.shift_id=$1 ORDER BY s.created_at DESC",[sh.id]),
 pool.query("SELECT t.*,n.code nozzle_code,m.code machine_code FROM nat_tests t JOIN nozzles n ON n.id=t.nozzle_id JOIN machines m ON m.id=n.machine_id WHERE t.shift_id=$1 ORDER BY t.created_at DESC",[sh.id]),
 pool.query('SELECT * FROM attendance WHERE shift_id=$1',[sh.id])
]);res.json({shift:sh,assignment:a.rows[0]||null,nozzles:nz.rows,sales:sales.rows,nat:nat.rows,attendance:att.rows[0]||null});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/salesman/digital',auth,roles('SALESMAN'),async(req,res)=>{try{const q=await pool.query("SELECT id,payment_mode,amount,settlement_status,created_at FROM collections WHERE station_id=$1 AND payment_mode IN ('UPI','CARD','BANK') ORDER BY created_at DESC LIMIT 100",[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Digital transactions failed'});}});
app.post('/api/salesman/nat',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const {shiftId,nozzleId,quantityL}=req.body;if(!shiftId||!nozzleId||n(quantityL)<=0)throw Error('Required NAT fields missing');const out=await tx(async c=>{const sh=(await c.query("SELECT id FROM shifts WHERE id=$1 AND station_id=$2 AND status='OPEN'",[shiftId,req.user.stationId])).rows[0];if(!sh)throw Error('Open shift required');const x=(await c.query(`INSERT INTO nat_tests(station_id,shift_id,nozzle_id,quantity_l,recorded_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.user.stationId,shiftId,nozzleId,quantityL,req.user.sub])).rows[0];await audit(c,req.user,'NAT',x.id,'CREATE',null,x,null);return x;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/credit-customers',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{if(!req.body.name)throw Error('Customer name required');const q=await pool.query(`INSERT INTO credit_customers(station_id,name,phone) VALUES($1,$2,$3) RETURNING *`,[req.user.stationId,req.body.name,req.body.phone||null]);res.status(201).json(q.rows[0]);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/dashboard',auth,roles('OWNER','MANAGER','SALESMAN'),async(req,res)=>{try{const s=req.user.stationId;const shiftQ=await pool.query("SELECT * FROM shifts WHERE station_id=$1 AND status='OPEN' ORDER BY starts_at DESC LIMIT 1",[s]);const shift=shiftQ.rows[0]||null;
 const [sales,collections,stock,pending,bank,variance]=await Promise.all([
  pool.query("SELECT COALESCE(SUM(amount),0) total,COALESCE(SUM(quantity_l),0) litres FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED') AND ($2::uuid IS NULL OR shift_id=$2)",[s,shift?.id||null]),
  pool.query("SELECT payment_mode,COALESCE(SUM(amount),0) total FROM collections WHERE station_id=$1 AND settlement_status IN ('VERIFIED','LOCKED') GROUP BY payment_mode",[s]),
  pool.query("SELECT p.code,p.name,COALESCE(SUM(i.quantity_remaining_l),0) litres FROM products p LEFT JOIN inventory_layers i ON i.product_id=p.id AND i.station_id=p.station_id WHERE p.station_id=$1 AND p.active=true GROUP BY p.id ORDER BY p.code",[s]),
  pool.query("SELECT (SELECT COUNT(*) FROM sales WHERE station_id=$1 AND status='PENDING') sales_pending,(SELECT COUNT(*) FROM bank_transactions WHERE station_id=$1 AND status='PENDING') bank_pending,(SELECT COUNT(*) FROM deliveries WHERE station_id=$1 AND pending_recovery_l>0) delivery_recovery_pending",[s]),
  pool.query("SELECT ba.id,ba.name,ba.account_mask,ba.opening_balance+COALESCE(SUM(CASE WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='IN' THEN bt.amount WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='OUT' THEN -bt.amount ELSE 0 END),0) balance FROM bank_accounts ba LEFT JOIN bank_transactions bt ON bt.bank_account_id=ba.id WHERE ba.station_id=$1 AND ba.active=true GROUP BY ba.id ORDER BY ba.name",[s]),
  pool.query("SELECT COUNT(*) count FROM reconciliation WHERE station_id=$1 AND status IN ('PENDING','ESCALATED')",[s])
 ]);
 const col=Object.fromEntries(collections.rows.map(r=>[r.payment_mode,n(r.total)]));
 const cashMove=shift?(await pool.query("SELECT COALESCE(SUM(CASE WHEN direction='IN' THEN amount ELSE -amount END),0) total FROM cash_movements WHERE shift_id=$1",[shift.id])).rows[0].total:0;const cashExpected=(shift?n(shift.opening_cash):0)+n(cashMove);
 res.json({shift,sales:sales.rows[0],collections:col,stock:stock.rows,pending:pending.rows[0],bank:bank.rows,expectedCash:cashExpected,exceptions:n(variance.rows[0].count)});
 }catch(e){res.status(500).json({error:'Dashboard failed'});}});

app.post('/api/shifts',auth,roles('MANAGER','SALESMAN'),async(req,res)=>{try{const {shiftType='DAY',startsAt=new Date().toISOString(),endsAt,openingCash=0}=req.body;const out=await tx(async c=>{const active=await c.query("SELECT id FROM shifts WHERE station_id=$1 AND status='OPEN' LIMIT 1 FOR UPDATE",[req.user.stationId]);if(active.rowCount)throw Error('An open shift already exists');const q=await c.query(`INSERT INTO shifts(station_id,opened_by,status,shift_type,starts_at,ends_at,opening_cash) VALUES($1,$2,'OPEN',$3,$4,$5,$6) RETURNING *`,[req.user.stationId,req.user.sub,shiftType,startsAt,endsAt||null,openingCash]);await audit(c,req.user,'SHIFT',q.rows[0].id,'OPEN',null,q.rows[0],null);return q.rows[0];});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/shifts/:id/close',auth,roles('MANAGER','SALESMAN'),async(req,res)=>{try{const out=await tx(async c=>{const q=await c.query('SELECT * FROM shifts WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount)throw Error('Shift not found');const sh=q.rows[0];if(sh.status!=='OPEN')throw Error('Shift is not open');if(sh.ends_at && Date.now()<new Date(sh.ends_at).getTime()-15*60*1000)throw Error('Close Shift unlocks in the final 15 minutes');for(const r of (req.body.nozzleReadings||[])){if(n(r.closingMeter)<0)throw Error('Invalid closing meter');await c.query('UPDATE shift_nozzle_readings SET closing_meter=$1 WHERE shift_id=$2 AND nozzle_id=$3',[r.closingMeter,sh.id,r.nozzleId]);await c.query('UPDATE nozzles SET opening_meter=$1 WHERE id=$2 AND station_id=$3',[r.closingMeter,r.nozzleId,req.user.stationId]);}const recon=(await c.query("SELECT id,status FROM reconciliation WHERE shift_id=$1",[sh.id])).rows[0];if(!recon||recon.status!=='RECONCILED')throw Error('Manager reconciliation is required before shift close');let actual=req.body.actualCash==null?null:n(req.body.actualCash);if(req.body.denominations){const d=req.body.denominations;actual=['2000','500','200','100','50','20','10','5','2','1'].reduce((sum,k)=>sum+n(d[k])*Number(k),0)+n(d.coins);if(actual<0)throw Error('Invalid denomination count');}if(actual==null)throw Error('Actual cash is required');const nrow=await c.query("UPDATE shifts SET status='CLOSED',closing_cash_actual=$1,locked_at=now(),locked_by=$2 WHERE id=$3 RETURNING *",[actual,req.user.sub,sh.id]);await c.query("UPDATE attendance SET completed_at=now(),status='COMPLETED' WHERE shift_id=$1",[sh.id]);await audit(c,req.user,'SHIFT',sh.id,'CLOSE',sh,nrow.rows[0],req.body.reason||null);return nrow.rows[0];});res.json(out);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/salesman/attendance',auth,roles('SALESMAN'),async(req,res)=>{try{const q=await pool.query('SELECT * FROM attendance WHERE station_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 100',[req.user.stationId,req.user.sub]);res.json(q.rows);}catch{res.status(500).json({error:'Attendance failed'});}});

app.get('/api/manager/overview',auth,roles('MANAGER'),async(req,res)=>{try{const s=req.user.stationId;const [dash,pending,expenses,collections,recons,deliveries]=await Promise.all([
 pool.query(`SELECT * FROM (SELECT * FROM shifts WHERE station_id=$1 ORDER BY starts_at DESC LIMIT 1) x`,[s]),
 pool.query(`SELECT sa.id,sa.amount,sa.quantity_l,sa.rate,sa.payment_mode,sa.nozzle,sa.customer_name,sa.company_name,sa.vehicle_no,sa.created_at,p.code product_code,u.name recorded_by_name,sa.shift_id FROM sales sa JOIN products p ON p.id=sa.product_id JOIN users u ON u.id=sa.recorded_by WHERE sa.station_id=$1 AND sa.status='PENDING' ORDER BY sa.created_at`,[s]),
 pool.query(`SELECT e.*,u.name recorded_by_name FROM expenses_v14 e JOIN users u ON u.id=e.recorded_by WHERE e.station_id=$1 ORDER BY e.created_at DESC LIMIT 50`,[s]),
 pool.query(`SELECT c.*,u.name recorded_by_name FROM collections c JOIN users u ON u.id=c.recorded_by WHERE c.station_id=$1 AND c.settlement_status='VERIFIED' ORDER BY c.created_at DESC LIMIT 100`,[s]),
 pool.query(`SELECT r.*,s.shift_type,s.starts_at,s.ends_at FROM reconciliation r JOIN shifts s ON s.id=r.shift_id WHERE r.station_id=$1 ORDER BY s.starts_at DESC LIMIT 20`,[s]),
 pool.query(`SELECT d.*,p.code product_code,t.name tank_name FROM deliveries d JOIN products p ON p.id=d.product_id JOIN tanks t ON t.id=d.tank_id WHERE d.station_id=$1 ORDER BY d.delivered_at DESC LIMIT 30`,[s])
]);
 const shift=dash.rows[0]||null;
 const cash=shift?(await pool.query(`SELECT COALESCE(SUM(CASE WHEN direction='IN' THEN amount ELSE -amount END),0) total FROM cash_movements WHERE shift_id=$1`,[shift.id])).rows[0].total:0;
 const expected=shift?n(shift.opening_cash)+n(cash):0;
 const bank=(await pool.query(`SELECT ba.id,ba.name,ba.account_mask,ba.opening_balance+COALESCE(SUM(CASE WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='IN' THEN bt.amount WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='OUT' THEN -bt.amount ELSE 0 END),0) balance FROM bank_accounts ba LEFT JOIN bank_transactions bt ON bt.bank_account_id=ba.id WHERE ba.station_id=$1 AND ba.active=true GROUP BY ba.id ORDER BY ba.name`,[s])).rows;
 const stock=(await pool.query(`SELECT p.code,p.name,COALESCE(SUM(i.quantity_remaining_l),0) litres FROM products p LEFT JOIN inventory_layers i ON i.product_id=p.id AND i.station_id=p.station_id WHERE p.station_id=$1 AND p.active=true GROUP BY p.id ORDER BY p.code`,[s])).rows;
 res.json({shift,pendingSales:pending.rows,expenses:expenses.rows,collections:collections.rows,reconciliations:recons.rows,deliveries:deliveries.rows,expectedCash:expected,bank,stock});
}catch(e){res.status(500).json({error:'Manager Overview Failed'});}});

app.get('/api/manager/shift/:id',auth,roles('MANAGER'),async(req,res)=>{try{const s=req.user.stationId,id=req.params.id;const sh=(await pool.query('SELECT * FROM shifts WHERE id=$1 AND station_id=$2',[id,s])).rows[0];if(!sh)throw Error('Shift Not Found');const [assignment,nozzles,sales,nat,recon,attendance,cash]=await Promise.all([
 pool.query(`SELECT a.*,m.code machine_code FROM shift_assignments a JOIN machines m ON m.id=a.machine_id WHERE a.shift_id=$1`,[id]),
 pool.query(`SELECT r.*,n.code nozzle_code,p.code product_code,m.code machine_code FROM shift_nozzle_readings r JOIN nozzles n ON n.id=r.nozzle_id JOIN products p ON p.id=n.product_id JOIN machines m ON m.id=n.machine_id WHERE r.shift_id=$1 ORDER BY n.code`,[id]),
 pool.query(`SELECT s.*,p.code product_code,p.name product_name,u.name recorded_by_name FROM sales s JOIN products p ON p.id=s.product_id JOIN users u ON u.id=s.recorded_by WHERE s.shift_id=$1 ORDER BY s.created_at`,[id]),
 pool.query('SELECT * FROM nat_tests WHERE shift_id=$1 ORDER BY created_at',[id]),
 pool.query('SELECT * FROM reconciliation WHERE shift_id=$1',[id]),
 pool.query('SELECT * FROM attendance WHERE shift_id=$1',[id]),
 pool.query(`SELECT COALESCE(SUM(CASE WHEN direction='IN' THEN amount ELSE -amount END),0) total FROM cash_movements WHERE shift_id=$1`,[id])
]);const expected=n(sh.opening_cash)+n(cash.rows[0].total);res.json({shift:sh,assignment:assignment.rows[0]||null,nozzles:nozzles.rows,sales:sales.rows,nat:nat.rows,reconciliation:recon.rows[0]||null,attendance:attendance.rows[0]||null,expectedCash:expected});}catch(e){res.status(400).json({error:e.message});}});

app.post('/api/expenses/:id/verify',auth,roles('MANAGER'),async(req,res)=>{try{const out=await tx(async c=>{const q=await c.query('SELECT * FROM expenses_v14 WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount)throw Error('Expense Not Found');const before=q.rows[0];const updated=(await c.query(`UPDATE expenses_v14 SET status='VERIFIED',verified_by=$1,verified_at=now() WHERE id=$2 RETURNING *`,[req.user.sub,before.id])).rows[0];await audit(c,req.user,'EXPENSE',before.id,'VERIFY',before,updated,req.body.reason||null);return updated;});res.json(out);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/sales',auth,roles('OWNER','MANAGER','SALESMAN'),async(req,res)=>{try{const q=await pool.query(`SELECT s.*,p.code product_code,p.name product_name,u.name recorded_by_name FROM sales s JOIN products p ON p.id=s.product_id JOIN users u ON u.id=s.recorded_by WHERE s.station_id=$1 ORDER BY s.created_at DESC LIMIT 200`,[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Sales failed'});}});
app.post('/api/sales',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const {shiftId,productId,nozzle,quantityL,rate,paymentMode,customerName,companyName,vehicleNo}=req.body;if(!shiftId||!productId||!nozzle||n(quantityL)<=0||n(rate)<0||!paymentMode)throw Error('Required sale fields missing');if(!['CASH','UPI','CARD','BANK','FLEET','CREDIT'].includes(paymentMode))throw Error('Invalid payment mode');if(paymentMode==='CREDIT'&&!customerName)throw Error('Credit customer required');if(paymentMode==='FLEET'&&!companyName)throw Error('Fleet/Company required');const out=await tx(async c=>{const old=await idem(req,c,req.path);if(old)return old;const sh=await c.query("SELECT id FROM shifts WHERE id=$1 AND station_id=$2 AND status='OPEN'",[shiftId,req.user.stationId]);if(!sh.rowCount)throw Error('Open shift required');const valid=(await c.query(`SELECT n.id FROM nozzles n JOIN shift_nozzle_readings r ON r.nozzle_id=n.id WHERE r.shift_id=$1 AND n.station_id=$2 AND n.code=$3 AND n.product_id=$4`,[shiftId,req.user.stationId,nozzle,productId])).rowCount;if(!valid)throw Error('Nozzle does not match selected fuel or shift');const q=await c.query(`INSERT INTO sales(station_id,shift_id,product_id,nozzle,quantity_l,rate,payment_mode,customer_name,company_name,vehicle_no,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.user.stationId,shiftId,productId,nozzle,quantityL,rate,paymentMode,customerName||null,companyName||null,vehicleNo||null,req.user.sub]);await audit(c,req.user,'SALE',q.rows[0].id,'CREATE',null,q.rows[0],null);await saveIdem(req,c,q.rows[0]);return q.rows[0];});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
async function consumeCost(c,station,product,qty){let remain=qty,total=0;const q=await c.query(`SELECT id,quantity_remaining_l,cost_per_l FROM inventory_layers WHERE station_id=$1 AND product_id=$2 AND quantity_remaining_l>0 ORDER BY created_at,id FOR UPDATE`,[station,product]);for(const r of q.rows){if(remain<=0)break;const take=Math.min(remain,n(r.quantity_remaining_l));total+=take*n(r.cost_per_l);await c.query('UPDATE inventory_layers SET quantity_remaining_l=quantity_remaining_l-$1 WHERE id=$2',[take,r.id]);remain-=take;}if(remain>0)throw Error('Insufficient verified inventory');return Number(total.toFixed(2));}
app.post('/api/sales/:id/verify',auth,roles('MANAGER'),async(req,res)=>{try{const out=await tx(async c=>{const q=await c.query('SELECT * FROM sales WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount)throw Error('Sale not found');const before=q.rows[0];if(before.status!=='PENDING')throw Error('Transaction is not pending');const cost=await consumeCost(c,req.user.stationId,before.product_id,n(before.quantity_l));const margin=n(before.amount)-cost;const sale=(await c.query(`UPDATE sales SET status='VERIFIED',verified_by=$1,verified_at=now(),cogs_amount=$2,margin_amount=$3 WHERE id=$4 RETURNING *`,[req.user.sub,cost,margin,before.id])).rows[0];const col=(await c.query(`INSERT INTO collections(station_id,shift_id,source_type,source_id,payment_mode,amount,settlement_status,recorded_by,verified_by,verified_at) VALUES($1,$2,'SALE',$3,$4,$5,'VERIFIED',$6,$6,now()) ON CONFLICT(source_type,source_id,payment_mode) DO UPDATE SET settlement_status='VERIFIED',verified_by=EXCLUDED.verified_by,verified_at=EXCLUDED.verified_at RETURNING *`,[req.user.stationId,before.shift_id,before.id,before.payment_mode,before.amount,req.user.sub])).rows[0];if(before.payment_mode==='CASH')await c.query(`INSERT INTO cash_movements(station_id,shift_id,source_type,source_id,direction,amount,purpose,recorded_by) VALUES($1,$2,'SALE',$3,'IN',$4,'Cash Sale',$5) ON CONFLICT DO NOTHING`,[req.user.stationId,before.shift_id,before.id,before.amount,req.user.sub]);await audit(c,req.user,'SALE',before.id,'VERIFY',before,sale,req.body.reason||null);return {sale,collection:col};});res.json(out);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/deliveries',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const q=await pool.query(`SELECT d.*,p.code product_code,p.name product_name,t.name tank_name FROM deliveries d JOIN products p ON p.id=d.product_id JOIN tanks t ON t.id=d.tank_id WHERE d.station_id=$1 ORDER BY d.delivered_at DESC LIMIT 100`,[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Deliveries failed'});}});
app.post('/api/deliveries',auth,roles('MANAGER'),async(req,res)=>{try{const {productId,tankId,invoiceNo,invoiceQtyL,invoiceValue,shortageL=0}=req.body;if(n(invoiceQtyL)<=0||n(invoiceValue)<0||n(shortageL)<0||n(shortageL)>n(invoiceQtyL))throw Error('Invalid delivery values');const out=await tx(async c=>{const d=(await c.query(`INSERT INTO deliveries(station_id,product_id,tank_id,invoice_no,invoice_qty_l,invoice_value,shortage_l,pending_recovery_l,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7,$8) RETURNING *`,[req.user.stationId,productId,tankId,invoiceNo||null,invoiceQtyL,invoiceValue,shortageL,req.user.sub])).rows[0];const layer=(await c.query(`INSERT INTO inventory_layers(station_id,product_id,delivery_id,quantity_received_l,quantity_remaining_l,cost_per_l) VALUES($1,$2,$3,$4,$4,$5) RETURNING *`,[req.user.stationId,productId,d.id,d.net_received_l,d.purchase_rate])).rows[0];await audit(c,req.user,'DELIVERY',d.id,'CREATE',null,d,null);return {delivery:d,inventoryLayer:layer};});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/deliveries/:id/recover',auth,roles('MANAGER'),async(req,res)=>{try{const out=await tx(async c=>{const q=await c.query('SELECT * FROM deliveries WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount)throw Error('Delivery not found');const d=q.rows[0],recover=n(req.body.quantityL);if(recover<=0||recover>n(d.pending_recovery_l))throw Error('Recovery exceeds pending shortage');const updated=(await c.query(`UPDATE deliveries SET recovery_l=recovery_l+$1,pending_recovery_l=pending_recovery_l-$1,recovery_status=CASE WHEN pending_recovery_l-$1=0 THEN 'RECOVERED'::delivery_recovery_status ELSE 'PARTIAL'::delivery_recovery_status END WHERE id=$2 RETURNING *`,[recover,d.id])).rows[0];await c.query(`INSERT INTO inventory_layers(station_id,product_id,delivery_id,quantity_received_l,quantity_remaining_l,cost_per_l) VALUES($1,$2,$3,$4,$4,$5)`,[req.user.stationId,d.product_id,d.id,recover,d.purchase_rate]);await audit(c,req.user,'DELIVERY',d.id,'RECOVERY',d,updated,req.body.reason||null);return updated;});res.json(out);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/banks',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const q=await pool.query(`SELECT ba.id,ba.name,ba.account_mask,ba.opening_balance+COALESCE(SUM(CASE WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='IN' THEN bt.amount WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='OUT' THEN -bt.amount ELSE 0 END),0) balance FROM bank_accounts ba LEFT JOIN bank_transactions bt ON bt.bank_account_id=ba.id WHERE ba.station_id=$1 AND ba.active=true GROUP BY ba.id ORDER BY ba.name`,[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Bank accounts failed'});}});
app.get('/api/bank-transactions',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const q=await pool.query(`SELECT bt.*,ba.name bank_name FROM bank_transactions bt JOIN bank_accounts ba ON ba.id=bt.bank_account_id WHERE bt.station_id=$1 ORDER BY bt.created_at DESC LIMIT 200`,[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Bank transactions failed'});}});
app.post('/api/bank-transactions',auth,roles('MANAGER'),async(req,res)=>{try{const {bankAccountId,type='OTHER',direction,amount,sourceType,sourceId,reference}=req.body;if(!bankAccountId||!['IN','OUT'].includes(direction)||n(amount)<=0)throw Error('Invalid bank movement');const out=await tx(async c=>{const old=await idem(req,c,req.path);if(old)return old;const q=(await c.query(`INSERT INTO bank_transactions(station_id,bank_account_id,type,direction,amount,source_type,source_id,reference,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.user.stationId,bankAccountId,type,direction,amount,sourceType||null,sourceId||null,reference||null,req.user.sub])).rows[0];await audit(c,req.user,'BANK_TRANSACTION',q.id,'CREATE',null,q,null);await saveIdem(req,c,q);return q;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/bank-transactions/:id/verify',auth,roles('MANAGER'),async(req,res)=>{try{const out=await tx(async c=>{const q=await c.query('SELECT * FROM bank_transactions WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount||q.rows[0].status!=='PENDING')throw Error('Pending bank transaction not found');const nrow=(await c.query("UPDATE bank_transactions SET status='VERIFIED',verified_by=$1,verified_at=now() WHERE id=$2 RETURNING *",[req.user.sub,req.params.id])).rows[0];await audit(c,req.user,'BANK_TRANSACTION',req.params.id,'VERIFY',q.rows[0],nrow,req.body.reason||null);return nrow;});res.json(out);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/collections',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const q=await pool.query('SELECT * FROM collections WHERE station_id=$1 ORDER BY created_at DESC LIMIT 200',[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Collections failed'});}});
app.post('/api/collections/:id/settle-bank',auth,roles('MANAGER'),async(req,res)=>{try{const out=await tx(async c=>{const q=await c.query('SELECT * FROM collections WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount)throw Error('Collection not found');const col=q.rows[0];if(!['UPI','CARD','BANK'].includes(col.payment_mode)||col.settlement_status!=='VERIFIED')throw Error('Collection is not eligible');if(!req.body.bankAccountId)throw Error('Bank account required');const b=(await c.query(`INSERT INTO bank_transactions(station_id,bank_account_id,type,direction,amount,source_type,source_id,reference,status,recorded_by,verified_by,verified_at) VALUES($1,$2,'DIGITAL_COLLECTION','IN',$3,'COLLECTION',$4,$5,'VERIFIED',$6,$6,now()) ON CONFLICT(source_type,source_id,type) DO UPDATE SET status='VERIFIED',verified_by=EXCLUDED.verified_by,verified_at=now() RETURNING *`,[req.user.stationId,req.body.bankAccountId,col.amount,col.id,req.body.reference||null,req.user.sub])).rows[0];const updated=(await c.query("UPDATE collections SET settlement_status='LOCKED',verified_by=$1,verified_at=now() WHERE id=$2 RETURNING *",[req.user.sub,col.id])).rows[0];await audit(c,req.user,'COLLECTION',col.id,'BANK_SETTLE',col,updated,req.body.reason||null);return {collection:updated,bankTransaction:b};});res.json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/collections/credit',auth,roles('MANAGER'),async(req,res)=>{try{const {shiftId,sourceId,amount,reference}=req.body;const out=await tx(async c=>{const q=(await c.query(`INSERT INTO collections(station_id,shift_id,source_type,source_id,payment_mode,amount,settlement_status,recorded_by,verified_by,verified_at) VALUES($1,$2,'CREDIT_PAYMENT',$3,'CREDIT',$4,'VERIFIED',$5,$5,now()) RETURNING *`,[req.user.stationId,shiftId,sourceId||crypto.randomUUID(),amount,req.user.sub])).rows[0];await audit(c,req.user,'COLLECTION',q.id,'CREDIT_COLLECTION',null,q,reference||null);return q;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/collections/fleet',auth,roles('MANAGER'),async(req,res)=>{try{const {shiftId,sourceId,amount,bankAccountId,reference}=req.body;const out=await tx(async c=>{const q=(await c.query(`INSERT INTO collections(station_id,shift_id,source_type,source_id,payment_mode,amount,settlement_status,recorded_by,verified_by,verified_at) VALUES($1,$2,'FLEET_SETTLEMENT',$3,'FLEET',$4,'VERIFIED',$5,$5,now()) RETURNING *`,[req.user.stationId,shiftId,sourceId||crypto.randomUUID(),amount,req.user.sub])).rows[0];if(bankAccountId)await c.query(`INSERT INTO bank_transactions(station_id,bank_account_id,type,direction,amount,source_type,source_id,reference,status,recorded_by,verified_by,verified_at) VALUES($1,$2,'FLEET_SETTLEMENT','IN',$3,'FLEET_SETTLEMENT',$4,$5,'VERIFIED',$6,$6,now()) ON CONFLICT(source_type,source_id,type) DO NOTHING`,[req.user.stationId,bankAccountId,amount,q.id,reference||null,req.user.sub]);await audit(c,req.user,'COLLECTION',q.id,'FLEET_SETTLEMENT',null,q,reference||null);return q;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});

app.post('/api/expenses',auth,roles('SALESMAN','MANAGER'),async(req,res)=>{try{const {shiftId,category='OTHER',amount,purpose,paymentMode='CASH'}=req.body;if(!shiftId||n(amount)<=0||!purpose)throw Error('Required expense fields missing');const out=await tx(async c=>{const sh=(await c.query("SELECT id FROM shifts WHERE id=$1 AND station_id=$2 AND status='OPEN'",[shiftId,req.user.stationId])).rows[0];if(!sh)throw Error('Open shift required');const x=(await c.query(`INSERT INTO expenses_v14(station_id,shift_id,category,amount,purpose,payment_mode,status,recorded_by) VALUES($1,$2,$3,$4,$5,$6,'PENDING',$7) RETURNING *`,[req.user.stationId,shiftId,category,amount,purpose,paymentMode,req.user.sub])).rows[0];if(paymentMode==='CASH')await c.query(`INSERT INTO cash_movements(station_id,shift_id,source_type,source_id,direction,amount,purpose,recorded_by) VALUES($1,$2,'EXPENSE',$3,'OUT',$4,$5,$6)`,[req.user.stationId,shiftId,x.id,amount,purpose,req.user.sub]);await audit(c,req.user,'EXPENSE',x.id,'CREATE',null,x,null);return x;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/expenses',auth,roles('OWNER','MANAGER','SALESMAN'),async(req,res)=>{try{const q=await pool.query('SELECT * FROM expenses_v14 WHERE station_id=$1 ORDER BY created_at DESC LIMIT 200',[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Expenses failed'});}});

app.get('/api/reconciliation',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const q=await pool.query(`SELECT r.*,s.shift_type,s.starts_at,s.ends_at FROM reconciliation r JOIN shifts s ON s.id=r.shift_id WHERE r.station_id=$1 ORDER BY s.starts_at DESC LIMIT 100`,[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Reconciliation failed'});}});
app.post('/api/reconciliation/:shiftId/decide',auth,roles('MANAGER'),async(req,res)=>{try{const out=await tx(async c=>{let q=await c.query('SELECT * FROM reconciliation WHERE shift_id=$1 AND station_id=$2 FOR UPDATE',[req.params.shiftId,req.user.stationId]);if(!q.rowCount){const sh=await c.query('SELECT * FROM shifts WHERE id=$1 AND station_id=$2',[req.params.shiftId,req.user.stationId]);if(!sh.rowCount)throw Error('Shift not found');const expected=n(sh.rows[0].opening_cash)+(await c.query("SELECT COALESCE(SUM(CASE WHEN direction='IN' THEN amount ELSE -amount END),0) x FROM cash_movements WHERE shift_id=$1",[req.params.shiftId])).rows[0].x;q=await c.query(`INSERT INTO reconciliation(station_id,shift_id,expected_cash) VALUES($1,$2,$3) RETURNING *`,[req.user.stationId,req.params.shiftId,expected]);}
 const before=q.rows[0],decision=req.body.decision,actual=req.body.actualCash==null?before.actual_cash:n(req.body.actualCash);if(!['RESOLVE','PENDING','ESCALATE'].includes(decision))throw Error('Invalid decision');const variance=actual==null?null:Number(actual)-n(before.expected_cash);if(decision==='RESOLVE'&&(variance==null||Math.abs(variance)>=0.01))throw Error('Cannot resolve with cash variance');const status=decision==='RESOLVE'?'RECONCILED':decision==='ESCALATE'?'ESCALATED':'PENDING';const updated=(await c.query(`UPDATE reconciliation SET actual_cash=$1,cash_variance=$2,status=$3,reason=$4,decided_by=$5,decided_at=now() WHERE id=$6 RETURNING *`,[actual,variance,status,req.body.reason||null,req.user.sub,before.id])).rows[0];await audit(c,req.user,'RECONCILIATION',before.id,'DECIDE',before,updated,req.body.reason||decision);return updated;});res.json(out);}catch(e){res.status(400).json({error:e.message});}});



// V16 Owner Control Module — oversight only; no operational entry points.
app.get('/api/configuration',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const s=req.user.stationId;const [products,tanks,machines,nozzles]=await Promise.all([pool.query('SELECT * FROM products WHERE station_id=$1 ORDER BY code',[s]),pool.query('SELECT t.*,p.code product_code,p.name product_name FROM tanks t JOIN products p ON p.id=t.product_id WHERE t.station_id=$1 ORDER BY t.name',[s]),pool.query('SELECT * FROM machines WHERE station_id=$1 ORDER BY code',[s]),pool.query('SELECT n.*,m.code machine_code,p.code product_code,p.name product_name FROM nozzles n JOIN machines m ON m.id=n.machine_id JOIN products p ON p.id=n.product_id WHERE n.station_id=$1 ORDER BY m.code,n.code',[s])]);res.json({products:products.rows,tanks:tanks.rows,machines:machines.rows,nozzles:nozzles.rows});}catch(e){res.status(500).json({error:'Configuration Failed'});}});
app.post('/api/configuration/product',auth,roles('OWNER'),async(req,res)=>{try{const {code,name}=req.body||{};if(!name)throw Error('Product Name Required');const q=await pool.query('INSERT INTO products(station_id,code,name) VALUES($1,$2,$3) RETURNING *',[req.user.stationId,String(code||name).toUpperCase().replace(/\\s+/g,'_'),name]);res.status(201).json(q.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/configuration/tank',auth,roles('OWNER'),async(req,res)=>{try{const {productId,name,capacity,openingStock=0,openingDip=0}=req.body||{};if(!productId||!name||n(capacity)<=0||n(openingStock)<0||n(openingDip)<0||n(openingStock)>n(capacity)||n(openingDip)>n(capacity))throw Error('Invalid Tank Details');const out=await tx(async c=>{const q=(await c.query('INSERT INTO tanks(station_id,product_id,name,capacity_l,opening_stock_l,opening_dip_l) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.user.stationId,productId,name,capacity,openingStock,openingDip])).rows[0];if(n(openingStock)>0)await c.query('INSERT INTO inventory_layers(station_id,product_id,quantity_received_l,quantity_remaining_l,cost_per_l) VALUES($1,$2,$3,$3,0)',[req.user.stationId,productId,openingStock]);await audit(c,req.user,'TANK',q.id,'CREATE',null,q,null);return q;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/configuration/machine',auth,roles('OWNER'),async(req,res)=>{try{const {code,name,nozzles=[]}=req.body||{};if(!name)throw Error('Machine Name Required');const out=await tx(async c=>{const m=(await c.query('INSERT INTO machines(station_id,code,name) VALUES($1,$2,$3) RETURNING *',[req.user.stationId,String(code||name).toUpperCase().replace(/\\s+/g,'_'),name])).rows[0];for(const z of nozzles){if(!z.productId)continue;await c.query('INSERT INTO nozzles(station_id,machine_id,code,product_id,opening_meter) VALUES($1,$2,$3,$4,$5)',[req.user.stationId,m.id,z.code||'N1',z.productId,z.openingMeter||0]);}return m;});res.status(201).json(out);}catch(e){res.status(400).json({error:e.message});}});

app.get('/api/owner/overview',auth,roles('OWNER'),async(req,res)=>{try{const s=req.user.stationId;const [shift,sales,collections,stock,bank,recons,pending,activity]=await Promise.all([
 pool.query("SELECT sh.*,u.name manager_name FROM shifts sh LEFT JOIN users u ON u.id=sh.opened_by WHERE sh.station_id=$1 ORDER BY sh.starts_at DESC LIMIT 1",[s]),
 pool.query("SELECT COALESCE(SUM(amount),0) sales,COALESCE(SUM(quantity_l),0) litres FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED') AND created_at>=date_trunc('day',now())",[s]),
 pool.query("SELECT payment_mode,COALESCE(SUM(amount),0) amount FROM collections WHERE station_id=$1 AND settlement_status IN ('VERIFIED','LOCKED') AND created_at>=date_trunc('day',now()) GROUP BY payment_mode",[s]),
 pool.query("SELECT p.code,p.name,COALESCE(SUM(i.quantity_remaining_l),0) litres FROM products p LEFT JOIN inventory_layers i ON i.product_id=p.id AND i.station_id=p.station_id WHERE p.station_id=$1 AND p.active=true GROUP BY p.id ORDER BY p.code",[s]),
 pool.query("SELECT ba.id,ba.name,ba.account_mask,ba.opening_balance+COALESCE(SUM(CASE WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='IN' THEN bt.amount WHEN bt.status IN ('VERIFIED','LOCKED') AND bt.direction='OUT' THEN -bt.amount ELSE 0 END),0) balance FROM bank_accounts ba LEFT JOIN bank_transactions bt ON bt.bank_account_id=ba.id WHERE ba.station_id=$1 AND ba.active=true GROUP BY ba.id ORDER BY ba.name",[s]),
 pool.query("SELECT r.*,sh.shift_type,sh.starts_at,sh.ends_at FROM reconciliation r JOIN shifts sh ON sh.id=r.shift_id WHERE r.station_id=$1 ORDER BY sh.starts_at DESC LIMIT 20",[s]),
 pool.query("SELECT (SELECT COUNT(*) FROM sales WHERE station_id=$1 AND status='PENDING') pending_sales,(SELECT COUNT(*) FROM bank_transactions WHERE station_id=$1 AND status='PENDING') pending_bank,(SELECT COUNT(*) FROM deliveries WHERE station_id=$1 AND pending_recovery_l>0) pending_delivery_recovery",[s]),
 pool.query("SELECT entity_type,action,reason,created_at FROM audit_events WHERE station_id=$1 ORDER BY created_at DESC LIMIT 12",[s])
]);
 const col=Object.fromEntries(collections.rows.map(x=>[x.payment_mode,n(x.amount)]));
 const exceptionRows=recons.rows.filter(x=>['PENDING','ESCALATED'].includes(x.status));
 const cashExpected=shift.rows[0]?(n(shift.rows[0].opening_cash)+(await pool.query("SELECT COALESCE(SUM(CASE WHEN direction='IN' THEN amount ELSE -amount END),0) total FROM cash_movements WHERE shift_id=$1",[shift.rows[0].id])).rows[0].total):0;
 const pnl=await ownerSummary(s,'DAY');
 res.json({shift:shift.rows[0]||null,sales:sales.rows[0],collections:col,stock:stock.rows,bank:bank.rows,reconciliations:recons.rows,pending:pending.rows[0],exceptions:exceptionRows.length,activity:activity.rows,pnl,expectedCash:cashExpected});
}catch(e){res.status(500).json({error:'Owner Overview Failed'});}});

async function ownerSummary(stationId,period){
 const ranges={DAY:"date_trunc('day',now())",WEEK:"date_trunc('week',now())",MONTH:"date_trunc('month',now())"};
 const start=ranges[period]||ranges.DAY;
 const [sales,delivery,expenses,variance,pending]=await Promise.all([
  pool.query(`SELECT COALESCE(SUM(amount),0) revenue,COALESCE(SUM(quantity_l),0) fuel_sold,COALESCE(SUM(cogs_amount),0) cogs,COALESCE(SUM(margin_amount),0) fuel_margin FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED') AND created_at>=${start}`,[stationId]),
  pool.query(`SELECT COALESCE(SUM(net_received_l),0) fuel_received FROM deliveries WHERE station_id=$1 AND delivered_at>=${start}`,[stationId]),
  pool.query(`SELECT COALESCE(SUM(amount),0) expenses FROM expenses_v14 WHERE station_id=$1 AND created_at>=${start}`,[stationId]),
  pool.query(`SELECT COUNT(*) exceptions FROM reconciliation WHERE station_id=$1 AND status IN ('PENDING','ESCALATED')`,[stationId]),
  pool.query(`SELECT (SELECT COUNT(*) FROM sales WHERE station_id=$1 AND status='PENDING') sales_pending,(SELECT COUNT(*) FROM bank_transactions WHERE station_id=$1 AND status='PENDING') bank_pending,(SELECT COUNT(*) FROM deliveries WHERE station_id=$1 AND pending_recovery_l>0) recovery_pending`,[stationId])
 ]);
 const x=sales.rows[0],e=n(expenses.rows[0].expenses);
 return {period,revenue:n(x.revenue),fuelSold:n(x.fuel_sold),fuelReceived:n(delivery.rows[0].fuel_received),cogs:n(x.cogs),fuelMargin:n(x.fuel_margin),expenses:e,profitLoss:n(x.fuel_margin)-e,exceptions:n(variance.rows[0].exceptions),pending:pending.rows[0]};
}
app.get('/api/owner/summary',auth,roles('OWNER'),async(req,res)=>{try{const p=req.query.period||'DAY';if(!['DAY','WEEK','MONTH'].includes(p))throw Error('Invalid period');res.json(await ownerSummary(req.user.stationId,p));}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/owner/reconciliation',auth,roles('OWNER'),async(req,res)=>{try{const q=await pool.query(`SELECT r.id,r.shift_id,r.expected_cash,r.actual_cash,r.cash_variance,r.status,r.reason,r.decided_at,r.owner_decision,r.owner_reason,sh.shift_type,sh.starts_at,sh.ends_at,u.name decided_by_name FROM reconciliation r JOIN shifts sh ON sh.id=r.shift_id LEFT JOIN users u ON u.id=r.decided_by WHERE r.station_id=$1 ORDER BY sh.starts_at DESC LIMIT 100`,[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Owner Reconciliation Failed'});}});
app.post('/api/owner/reconciliation/:id/decide',auth,roles('OWNER'),async(req,res)=>{try{const {decision,reason}=req.body||{};if(!['APPROVE_EXCEPTION','RETURN_TO_MANAGER'].includes(decision))throw Error('Invalid owner decision');const out=await tx(async c=>{const q=await c.query('SELECT * FROM reconciliation WHERE id=$1 AND station_id=$2 FOR UPDATE',[req.params.id,req.user.stationId]);if(!q.rowCount)throw Error('Reconciliation not found');if(q.rows[0].status!=='ESCALATED')throw Error('Only escalated reconciliation requires owner decision');const status=decision==='APPROVE_EXCEPTION'?'OWNER_APPROVED':'PENDING';const updated=(await c.query(`UPDATE reconciliation SET status=$1,owner_decision=$2,owner_reason=$3 WHERE id=$4 RETURNING *`,[status,decision,reason||null,req.params.id])).rows[0];await audit(c,req.user,'RECONCILIATION',updated.id,'OWNER_DECISION',q.rows[0],updated,reason||decision);return updated;});res.json(out);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/owner/reports',auth,roles('OWNER'),async(req,res)=>{try{const [sales,cash,fuel,deliveries,credit,fleet]=await Promise.all([
 pool.query("SELECT date_trunc('day',created_at)::date day,COALESCE(SUM(amount),0) sales,COALESCE(SUM(margin_amount),0) margin FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED') GROUP BY 1 ORDER BY 1 DESC LIMIT 31",[req.user.stationId]),
 pool.query("SELECT payment_mode,COALESCE(SUM(amount),0) amount FROM collections WHERE station_id=$1 AND settlement_status IN ('VERIFIED','LOCKED') GROUP BY payment_mode ORDER BY payment_mode",[req.user.stationId]),
 pool.query("SELECT p.code,p.name,COALESCE(SUM(s.quantity_l),0) sold_l FROM products p LEFT JOIN sales s ON s.product_id=p.id AND s.status IN ('VERIFIED','LOCKED') WHERE p.station_id=$1 GROUP BY p.id ORDER BY p.code",[req.user.stationId]),
 pool.query("SELECT COUNT(*) deliveries,COALESCE(SUM(net_received_l),0) received_l,COALESCE(SUM(shortage_l),0) recoverable_shortage_l FROM deliveries WHERE station_id=$1",[req.user.stationId]),
 pool.query("SELECT COALESCE(SUM(CASE WHEN payment_mode='CREDIT' THEN amount ELSE 0 END),0) credit_sales FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED')",[req.user.stationId]),
 pool.query("SELECT COALESCE(SUM(CASE WHEN payment_mode='FLEET' THEN amount ELSE 0 END),0) fleet_sales FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED')",[req.user.stationId])
]);res.json({dailySales:sales.rows,collections:cash.rows,fuel:fuel.rows,deliveries:deliveries.rows[0],credit:credit.rows[0],fleet:fleet.rows[0]});}catch{res.status(500).json({error:'Owner Reports Failed'});}});
app.get('/api/owner/settings',auth,roles('OWNER'),async(req,res)=>{try{const s=req.user.stationId;const [station,users,products,tanks,machines]=await Promise.all([
 pool.query('SELECT id,name,timezone,currency FROM stations WHERE id=$1',[s]),
 pool.query('SELECT id,name,mobile,role,active FROM users WHERE station_id=$1 ORDER BY role,name',[s]),
 pool.query('SELECT id,code,name,active FROM products WHERE station_id=$1 ORDER BY code',[s]),
 pool.query('SELECT t.id,t.name,t.capacity_l,p.code product_code,t.active FROM tanks t JOIN products p ON p.id=t.product_id WHERE t.station_id=$1 ORDER BY t.name',[s]),
 pool.query('SELECT m.id,m.code,m.name,m.active,COUNT(n.id)::int nozzle_count FROM machines m LEFT JOIN nozzles n ON n.machine_id=m.id AND n.active=true WHERE m.station_id=$1 GROUP BY m.id ORDER BY m.code',[s])
]);res.json({station:station.rows[0],users:users.rows,products:products.rows,tanks:tanks.rows,machines:machines.rows});}catch{res.status(500).json({error:'Owner Settings Failed'});}});

app.get('/api/pnl',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const s=req.user.stationId;const [q,e]=await Promise.all([pool.query("SELECT COALESCE(SUM(amount),0) revenue,COALESCE(SUM(cogs_amount),0) cogs,COALESCE(SUM(margin_amount),0) fuel_margin FROM sales WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED')",[s]),pool.query("SELECT COALESCE(SUM(amount),0) expenses FROM expenses_v14 WHERE station_id=$1 AND status IN ('VERIFIED','LOCKED')",[s])]);const p=q.rows[0],ex=n(e.rows[0].expenses);res.json({revenue:n(p.revenue),cogs:n(p.cogs),fuel_margin:n(p.fuel_margin),expenses:ex,netOperatingProfit:n(p.fuel_margin)-ex});}catch{res.status(500).json({error:'P&L failed'});}});
app.get('/api/audit',auth,roles('OWNER','MANAGER'),async(req,res)=>{try{const q=await pool.query('SELECT id,actor_id,entity_type,entity_id,action,before_json,after_json,reason,request_id,created_at FROM audit_events WHERE station_id=$1 ORDER BY created_at DESC LIMIT 500',[req.user.stationId]);res.json(q.rows);}catch{res.status(500).json({error:'Audit failed'});}});
app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});res.sendFile(path.join(__dirname,'../public/index.html'));});
if(!process.env.VERCEL)app.listen(PORT,()=>console.log(`PumpOS API running on :${PORT}`));
export default app;
